# Generated by Django 5.2 on 2025-09-10 01:35

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('candidate_name', models.CharField(max_length=100)),
                ('manifesto', models.TextField(blank=True, null=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('supporters', models.JSONField(blank=True, default=list, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('structure', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('x', models.URLField(blank=True, max_length=255, null=True)),
                ('threads', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyImpressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Impression',
                'verbose_name_plural': 'Daily Impressions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('party_name', models.CharField(max_length=100)),
                ('manifesto', models.TextField(blank=True, null=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('supporters', models.JSONField(blank=True, default=list, null=True)),
                ('party_leader', models.CharField(blank=True, max_length=100, null=True)),
                ('structure', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('x', models.URLField(blank=True, max_length=255, null=True)),
                ('threads', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('candidate', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('structure', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('privacy_settings', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=7)),
                ('user_facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('user_instagram', models.TextField(blank=True, max_length=255, null=True)),
                ('user_x_twitter', models.TextField(blank=True, max_length=255, null=True)),
                ('user_threads', models.TextField(blank=True, max_length=255, null=True)),
                ('user_youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('user_linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('user_tiktok', models.TextField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(max_length=500)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('videos', models.JSONField(blank=True, default=list, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('user_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('comments', models.JSONField(blank=True, default=list, null=True)),
                ('parties', models.ManyToManyField(blank=True, related_name='posts', to='somaapp.parties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
